name: Build OpenWrt

on:
  release:
    types: published
  push:
    branches:
      - master
      - dev
      - actions-dev
    paths:
      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: started

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: .config
  DIY_SH: diy.sh
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  CREATE_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    if: |
      false
      && github.event.repository.owner.id == github.event.sender.id
    

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Compile the firmware
      id: compile
      run: |
        mkdir temp
        cd temp
        echo  ${{ github.sha }} > test.csv
        echo  ${{ github.sha }} > test1.csv

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt_firmware
        path: temp

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate Changelog
      run: echo "# Good things have arrived" > CHANGELOG.txt

    - name: Read CHANGELOG
      id: changelog
      run: |
        echo "::set-output name=body::$(cat CHANGELOG.txt)"

    - name: Download Firmware Directory
      uses: actions/download-artifact@v1
      with:
        name: OpenWrt_firmware

    # - name: GH Release
    #   uses: softprops/action-gh-release@v0.1.5
    #   with:
    #     body_path: ${{ github.workflow }}-CHANGELOG.txt
    #     files: |
    #       test.csv
    #       test1.csv
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     input_tag_name: ${{ github.ref }}
    #     github_ref: refs/tags/233




    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.sha }}
        body: ${{ steps.changelog.outputs.body }}
        draft: true
        prerelease: true

    - name: Upload Release Asset1
      id: upload-release-asset1 
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: OpenWrt_firmware/test.csv
        asset_name: test.csv
        asset_content_type: text/csv # application/zip

    - name: Upload Release Asset2
      id: upload-release-asset2 
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: OpenWrt_firmware/test1.csv
        asset_name: test1.csv
        asset_content_type: text/csv # application/zip
